openapi: 3.0.1
info:
  title: Agenda ChatGPT API
  description: API para integração do ChatGPT com o Google Calendar via Apps Script.
  version: '1.0'

paths:
  /freebusy:
    get:
      summary: Verificar disponibilidade de horário
      parameters:
        - name: timeMin
          in: query
          required: true
          description: Início do intervalo (formato RFC3339)
          schema:
            type: string
        - name: timeMax
          in: query
          required: true
          description: Fim do intervalo (formato RFC3339)
          schema:
            type: string
      responses:
        '200':
          description: Lista de períodos ocupados
          content:
            application/json:
              schema:
                type: object

  /events:
    post:
      summary: Criar um novo evento no Google Calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                description:
                  type: string
                start:
                  type: string
                end:
                  type: string
      responses:
        '200':
          description: Evento criado com sucesso
          content:
            application/json:
              schema:
                type: object
